# Note: This file is produced automatically, and will be overwritten the next
# time you press "Generate" in System Generator. 
#


namespace eval ::xilinx::dsp::planaheaddriver {
	set Compilation {IP Catalog}
	set CompilationFlow {IP}
	set CreateInterfaceDocument {off}
	set DSPDevice {xczu28dr}
	set DSPFamily {zynquplus}
	set DSPPackage {ffvg1517}
	set DSPSpeed {-2-e}
	set FPGAClockPeriod 39.0625
	set GenerateTestBench 0
	set HDLLanguage {vhdl}
	set IPOOCCacheRootPath {C:/Users/david/AppData/Local/Xilinx/Sysgen/SysgenVivado/win64.o/ip}
	set IP_Auto_Infer {1}
	set IP_Categories_Text {RFSoC Custom IP Cores}
	set IP_Common_Repos {0}
	set IP_Description {}
	set IP_Dir {}
	set IP_Library_Text {RFSoC}
	set IP_LifeCycle_Menu {2}
	set IP_Logo {sysgen_icon_100.png}
	set IP_Name {AXI_QPSK_Tx}
	set IP_Revision {233583364}
	set IP_Socket_IP {0}
	set IP_Socket_IP_Proj_Path {}
	set IP_Vendor_Text {UoS}
	set IP_Version_Text {5.2}
	set ImplStrategyName {Vivado Implementation Defaults}
	set PostProjectCreationProc {dsp_package_for_vivado_ip_integrator}
	set Project {axi_qpsk_tx}
	set ProjectFiles {
		{{conv_pkg.vhd} -lib {xil_defaultlib}}
		{{synth_reg.vhd} -lib {xil_defaultlib}}
		{{synth_reg_w_init.vhd} -lib {xil_defaultlib}}
		{{srl17e.vhd} -lib {xil_defaultlib}}
		{{srl33e.vhd} -lib {xil_defaultlib}}
		{{synth_reg_reg.vhd} -lib {xil_defaultlib}}
		{{single_reg_w_init.vhd} -lib {xil_defaultlib}}
		{{xlclockdriver_rd.vhd} -lib {xil_defaultlib}}
		{{vivado_ip.tcl}}
		{{xlaxi_qpsk_tx_xfft_v9_1_i0_721f9082826645792fb18bff206302d6.v}}
		{{conv_pkg.v}}
		{{synth_reg.v}}
		{{synth_reg_w_init.v}}
		{{convert_type.v}}
		{{axi_qpsk_tx_axi_lite_interface_verilog.v}}
		{{conv_pkg.v}}
		{{synth_reg.v}}
		{{synth_reg_w_init.v}}
		{{convert_type.v}}
		{{axi_qpsk_tx.mdd}}
		{{axi_qpsk_tx_hw.h}}
		{{axi_qpsk_tx.h}}
		{{axi_qpsk_tx_sinit.c}}
		{{axi_qpsk_tx.c}}
		{{axi_qpsk_tx_linux.c}}
		{{axi_qpsk_tx.mtcl}}
		{{Makefile.mak}}
		{{index.html}}
		{{axi_qpsk_tx_entity_declarations.vhd} -lib {xil_defaultlib}}
		{{axi_qpsk_tx.vhd} -lib {xil_defaultlib}}
		{{axi_qpsk_tx_clock.xdc}}
		{{axi_qpsk_tx.xdc}}
	}
	set SimPeriod 3.90625e-08
	set SimTime 1
	set SimulationTime {1000000239.06249988 ns}
	set SynthStrategyName {Vivado Synthesis Defaults}
	set SynthesisTool {Vivado}
	set TargetDir {C:/GitHub/strath_sdr/rfsoc_qpsk/boards/ip/sysgen/iprepo/zcu111/tx}
	set TopLevelModule {axi_qpsk_tx}
	set TopLevelSimulinkHandle 0.000732422
	set VHDLLib {xil_defaultlib}
	set TopLevelPortInterface {}
	dict set TopLevelPortInterface m_time_axis_tready Name {m_time_axis_tready}
	dict set TopLevelPortInterface m_time_axis_tready Type Bool
	dict set TopLevelPortInterface m_time_axis_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_time_axis_tready BinaryPoint 0
	dict set TopLevelPortInterface m_time_axis_tready Width 1
	dict set TopLevelPortInterface m_time_axis_tready DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_time_m_time_axis_tready.dat}
	dict set TopLevelPortInterface m_time_axis_tready IconText {m_time_axis_tready}
	dict set TopLevelPortInterface m_time_axis_tready Direction in
	dict set TopLevelPortInterface m_time_axis_tready Period 1
	dict set TopLevelPortInterface m_time_axis_tready Interface 0
	dict set TopLevelPortInterface m_time_axis_tready InterfaceName {}
	dict set TopLevelPortInterface m_time_axis_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_time_axis_tready ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_time_axis_tready Locs {}
	dict set TopLevelPortInterface m_time_axis_tready IOStandard {}
	dict set TopLevelPortInterface m_symbol_axis_tready Name {m_symbol_axis_tready}
	dict set TopLevelPortInterface m_symbol_axis_tready Type Bool
	dict set TopLevelPortInterface m_symbol_axis_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_symbol_axis_tready BinaryPoint 0
	dict set TopLevelPortInterface m_symbol_axis_tready Width 1
	dict set TopLevelPortInterface m_symbol_axis_tready DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_symbol_m_symbol_axis_tready.dat}
	dict set TopLevelPortInterface m_symbol_axis_tready IconText {m_symbol_axis_tready}
	dict set TopLevelPortInterface m_symbol_axis_tready Direction in
	dict set TopLevelPortInterface m_symbol_axis_tready Period 1
	dict set TopLevelPortInterface m_symbol_axis_tready Interface 0
	dict set TopLevelPortInterface m_symbol_axis_tready InterfaceName {}
	dict set TopLevelPortInterface m_symbol_axis_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_symbol_axis_tready ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_symbol_axis_tready Locs {}
	dict set TopLevelPortInterface m_symbol_axis_tready IOStandard {}
	dict set TopLevelPortInterface m_fft_axis_tready Name {m_fft_axis_tready}
	dict set TopLevelPortInterface m_fft_axis_tready Type Bool
	dict set TopLevelPortInterface m_fft_axis_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_fft_axis_tready BinaryPoint 0
	dict set TopLevelPortInterface m_fft_axis_tready Width 1
	dict set TopLevelPortInterface m_fft_axis_tready DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_fft_m_fft_axis_tready.dat}
	dict set TopLevelPortInterface m_fft_axis_tready IconText {m_fft_axis_tready}
	dict set TopLevelPortInterface m_fft_axis_tready Direction in
	dict set TopLevelPortInterface m_fft_axis_tready Period 1
	dict set TopLevelPortInterface m_fft_axis_tready Interface 0
	dict set TopLevelPortInterface m_fft_axis_tready InterfaceName {}
	dict set TopLevelPortInterface m_fft_axis_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_fft_axis_tready ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_fft_axis_tready Locs {}
	dict set TopLevelPortInterface m_fft_axis_tready IOStandard {}
	dict set TopLevelPortInterface m_rf_axis_tready Name {m_rf_axis_tready}
	dict set TopLevelPortInterface m_rf_axis_tready Type Bool
	dict set TopLevelPortInterface m_rf_axis_tready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_rf_axis_tready BinaryPoint 0
	dict set TopLevelPortInterface m_rf_axis_tready Width 1
	dict set TopLevelPortInterface m_rf_axis_tready DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_m_rf_axis_tready.dat}
	dict set TopLevelPortInterface m_rf_axis_tready IconText {m_rf_axis_tready}
	dict set TopLevelPortInterface m_rf_axis_tready Direction in
	dict set TopLevelPortInterface m_rf_axis_tready Period 1
	dict set TopLevelPortInterface m_rf_axis_tready Interface 0
	dict set TopLevelPortInterface m_rf_axis_tready InterfaceName {}
	dict set TopLevelPortInterface m_rf_axis_tready InterfaceString {DATA}
	dict set TopLevelPortInterface m_rf_axis_tready ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_rf_axis_tready Locs {}
	dict set TopLevelPortInterface m_rf_axis_tready IOStandard {}
	dict set TopLevelPortInterface m_rf_axis_tdata Name {m_rf_axis_tdata}
	dict set TopLevelPortInterface m_rf_axis_tdata Type UFix_32_0
	dict set TopLevelPortInterface m_rf_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_rf_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_rf_axis_tdata Width 32
	dict set TopLevelPortInterface m_rf_axis_tdata DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_m_rf_axis_tdata.dat}
	dict set TopLevelPortInterface m_rf_axis_tdata IconText {m_rf_axis_tdata}
	dict set TopLevelPortInterface m_rf_axis_tdata Direction out
	dict set TopLevelPortInterface m_rf_axis_tdata Period 1
	dict set TopLevelPortInterface m_rf_axis_tdata Interface 0
	dict set TopLevelPortInterface m_rf_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface m_rf_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_rf_axis_tdata ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_rf_axis_tdata Locs {}
	dict set TopLevelPortInterface m_rf_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_rf_axis_tlast Name {m_rf_axis_tlast}
	dict set TopLevelPortInterface m_rf_axis_tlast Type Bool
	dict set TopLevelPortInterface m_rf_axis_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_rf_axis_tlast BinaryPoint 0
	dict set TopLevelPortInterface m_rf_axis_tlast Width 1
	dict set TopLevelPortInterface m_rf_axis_tlast DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_m_rf_axis_tlast.dat}
	dict set TopLevelPortInterface m_rf_axis_tlast IconText {m_rf_axis_tlast}
	dict set TopLevelPortInterface m_rf_axis_tlast Direction out
	dict set TopLevelPortInterface m_rf_axis_tlast Period 1
	dict set TopLevelPortInterface m_rf_axis_tlast Interface 0
	dict set TopLevelPortInterface m_rf_axis_tlast InterfaceName {}
	dict set TopLevelPortInterface m_rf_axis_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface m_rf_axis_tlast ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_rf_axis_tlast Locs {}
	dict set TopLevelPortInterface m_rf_axis_tlast IOStandard {}
	dict set TopLevelPortInterface m_rf_axis_tvalid Name {m_rf_axis_tvalid}
	dict set TopLevelPortInterface m_rf_axis_tvalid Type Bool
	dict set TopLevelPortInterface m_rf_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_rf_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_rf_axis_tvalid Width 1
	dict set TopLevelPortInterface m_rf_axis_tvalid DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_m_rf_axis_tvalid.dat}
	dict set TopLevelPortInterface m_rf_axis_tvalid IconText {m_rf_axis_tvalid}
	dict set TopLevelPortInterface m_rf_axis_tvalid Direction out
	dict set TopLevelPortInterface m_rf_axis_tvalid Period 1
	dict set TopLevelPortInterface m_rf_axis_tvalid Interface 0
	dict set TopLevelPortInterface m_rf_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_rf_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_rf_axis_tvalid ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_rf_axis_tvalid Locs {}
	dict set TopLevelPortInterface m_rf_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface m_fft_axis_tdata Name {m_fft_axis_tdata}
	dict set TopLevelPortInterface m_fft_axis_tdata Type UFix_32_0
	dict set TopLevelPortInterface m_fft_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_fft_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_fft_axis_tdata Width 32
	dict set TopLevelPortInterface m_fft_axis_tdata DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_fft_m_fft_axis_tdata.dat}
	dict set TopLevelPortInterface m_fft_axis_tdata IconText {m_fft_axis_tdata}
	dict set TopLevelPortInterface m_fft_axis_tdata Direction out
	dict set TopLevelPortInterface m_fft_axis_tdata Period 1
	dict set TopLevelPortInterface m_fft_axis_tdata Interface 0
	dict set TopLevelPortInterface m_fft_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface m_fft_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_fft_axis_tdata ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_fft_axis_tdata Locs {}
	dict set TopLevelPortInterface m_fft_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_fft_axis_tlast Name {m_fft_axis_tlast}
	dict set TopLevelPortInterface m_fft_axis_tlast Type Bool
	dict set TopLevelPortInterface m_fft_axis_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_fft_axis_tlast BinaryPoint 0
	dict set TopLevelPortInterface m_fft_axis_tlast Width 1
	dict set TopLevelPortInterface m_fft_axis_tlast DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_fft_m_fft_axis_tlast.dat}
	dict set TopLevelPortInterface m_fft_axis_tlast IconText {m_fft_axis_tlast}
	dict set TopLevelPortInterface m_fft_axis_tlast Direction out
	dict set TopLevelPortInterface m_fft_axis_tlast Period 1
	dict set TopLevelPortInterface m_fft_axis_tlast Interface 0
	dict set TopLevelPortInterface m_fft_axis_tlast InterfaceName {}
	dict set TopLevelPortInterface m_fft_axis_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface m_fft_axis_tlast ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_fft_axis_tlast Locs {}
	dict set TopLevelPortInterface m_fft_axis_tlast IOStandard {}
	dict set TopLevelPortInterface m_fft_axis_tvalid Name {m_fft_axis_tvalid}
	dict set TopLevelPortInterface m_fft_axis_tvalid Type Bool
	dict set TopLevelPortInterface m_fft_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_fft_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_fft_axis_tvalid Width 1
	dict set TopLevelPortInterface m_fft_axis_tvalid DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_fft_m_fft_axis_tvalid.dat}
	dict set TopLevelPortInterface m_fft_axis_tvalid IconText {m_fft_axis_tvalid}
	dict set TopLevelPortInterface m_fft_axis_tvalid Direction out
	dict set TopLevelPortInterface m_fft_axis_tvalid Period 1
	dict set TopLevelPortInterface m_fft_axis_tvalid Interface 0
	dict set TopLevelPortInterface m_fft_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_fft_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_fft_axis_tvalid ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_fft_axis_tvalid Locs {}
	dict set TopLevelPortInterface m_fft_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface m_symbol_axis_tdata Name {m_symbol_axis_tdata}
	dict set TopLevelPortInterface m_symbol_axis_tdata Type UFix_8_0
	dict set TopLevelPortInterface m_symbol_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_symbol_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_symbol_axis_tdata Width 8
	dict set TopLevelPortInterface m_symbol_axis_tdata DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_symbol_m_symbol_axis_tdata.dat}
	dict set TopLevelPortInterface m_symbol_axis_tdata IconText {m_symbol_axis_tdata}
	dict set TopLevelPortInterface m_symbol_axis_tdata Direction out
	dict set TopLevelPortInterface m_symbol_axis_tdata Period 1
	dict set TopLevelPortInterface m_symbol_axis_tdata Interface 0
	dict set TopLevelPortInterface m_symbol_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface m_symbol_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_symbol_axis_tdata ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_symbol_axis_tdata Locs {}
	dict set TopLevelPortInterface m_symbol_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_symbol_axis_tlast Name {m_symbol_axis_tlast}
	dict set TopLevelPortInterface m_symbol_axis_tlast Type Bool
	dict set TopLevelPortInterface m_symbol_axis_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_symbol_axis_tlast BinaryPoint 0
	dict set TopLevelPortInterface m_symbol_axis_tlast Width 1
	dict set TopLevelPortInterface m_symbol_axis_tlast DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_symbol_m_symbol_axis_tlast.dat}
	dict set TopLevelPortInterface m_symbol_axis_tlast IconText {m_symbol_axis_tlast}
	dict set TopLevelPortInterface m_symbol_axis_tlast Direction out
	dict set TopLevelPortInterface m_symbol_axis_tlast Period 1
	dict set TopLevelPortInterface m_symbol_axis_tlast Interface 0
	dict set TopLevelPortInterface m_symbol_axis_tlast InterfaceName {}
	dict set TopLevelPortInterface m_symbol_axis_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface m_symbol_axis_tlast ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_symbol_axis_tlast Locs {}
	dict set TopLevelPortInterface m_symbol_axis_tlast IOStandard {}
	dict set TopLevelPortInterface m_symbol_axis_tvalid Name {m_symbol_axis_tvalid}
	dict set TopLevelPortInterface m_symbol_axis_tvalid Type Bool
	dict set TopLevelPortInterface m_symbol_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_symbol_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_symbol_axis_tvalid Width 1
	dict set TopLevelPortInterface m_symbol_axis_tvalid DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_symbol_m_symbol_axis_tvalid.dat}
	dict set TopLevelPortInterface m_symbol_axis_tvalid IconText {m_symbol_axis_tvalid}
	dict set TopLevelPortInterface m_symbol_axis_tvalid Direction out
	dict set TopLevelPortInterface m_symbol_axis_tvalid Period 1
	dict set TopLevelPortInterface m_symbol_axis_tvalid Interface 0
	dict set TopLevelPortInterface m_symbol_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_symbol_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_symbol_axis_tvalid ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_symbol_axis_tvalid Locs {}
	dict set TopLevelPortInterface m_symbol_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface m_time_axis_tdata Name {m_time_axis_tdata}
	dict set TopLevelPortInterface m_time_axis_tdata Type UFix_32_0
	dict set TopLevelPortInterface m_time_axis_tdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_time_axis_tdata BinaryPoint 0
	dict set TopLevelPortInterface m_time_axis_tdata Width 32
	dict set TopLevelPortInterface m_time_axis_tdata DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_time_m_time_axis_tdata.dat}
	dict set TopLevelPortInterface m_time_axis_tdata IconText {m_time_axis_tdata}
	dict set TopLevelPortInterface m_time_axis_tdata Direction out
	dict set TopLevelPortInterface m_time_axis_tdata Period 1
	dict set TopLevelPortInterface m_time_axis_tdata Interface 0
	dict set TopLevelPortInterface m_time_axis_tdata InterfaceName {}
	dict set TopLevelPortInterface m_time_axis_tdata InterfaceString {DATA}
	dict set TopLevelPortInterface m_time_axis_tdata ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_time_axis_tdata Locs {}
	dict set TopLevelPortInterface m_time_axis_tdata IOStandard {}
	dict set TopLevelPortInterface m_time_axis_tlast Name {m_time_axis_tlast}
	dict set TopLevelPortInterface m_time_axis_tlast Type Bool
	dict set TopLevelPortInterface m_time_axis_tlast ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_time_axis_tlast BinaryPoint 0
	dict set TopLevelPortInterface m_time_axis_tlast Width 1
	dict set TopLevelPortInterface m_time_axis_tlast DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_time_m_time_axis_tlast.dat}
	dict set TopLevelPortInterface m_time_axis_tlast IconText {m_time_axis_tlast}
	dict set TopLevelPortInterface m_time_axis_tlast Direction out
	dict set TopLevelPortInterface m_time_axis_tlast Period 1
	dict set TopLevelPortInterface m_time_axis_tlast Interface 0
	dict set TopLevelPortInterface m_time_axis_tlast InterfaceName {}
	dict set TopLevelPortInterface m_time_axis_tlast InterfaceString {DATA}
	dict set TopLevelPortInterface m_time_axis_tlast ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_time_axis_tlast Locs {}
	dict set TopLevelPortInterface m_time_axis_tlast IOStandard {}
	dict set TopLevelPortInterface m_time_axis_tvalid Name {m_time_axis_tvalid}
	dict set TopLevelPortInterface m_time_axis_tvalid Type Bool
	dict set TopLevelPortInterface m_time_axis_tvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface m_time_axis_tvalid BinaryPoint 0
	dict set TopLevelPortInterface m_time_axis_tvalid Width 1
	dict set TopLevelPortInterface m_time_axis_tvalid DatFile {axi_qpsk_tx_axi_qpsk_generator_m_axis_time_m_time_axis_tvalid.dat}
	dict set TopLevelPortInterface m_time_axis_tvalid IconText {m_time_axis_tvalid}
	dict set TopLevelPortInterface m_time_axis_tvalid Direction out
	dict set TopLevelPortInterface m_time_axis_tvalid Period 1
	dict set TopLevelPortInterface m_time_axis_tvalid Interface 0
	dict set TopLevelPortInterface m_time_axis_tvalid InterfaceName {}
	dict set TopLevelPortInterface m_time_axis_tvalid InterfaceString {DATA}
	dict set TopLevelPortInterface m_time_axis_tvalid ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface m_time_axis_tvalid Locs {}
	dict set TopLevelPortInterface m_time_axis_tvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Name {axi_qpsk_tx_aresetn}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Type -
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn IconText {axi_qpsk_tx_aresetn}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Interface 8
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn InterfaceString {ARESETN}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_aresetn IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Name {axi_qpsk_tx_s_axi_awaddr}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Width 7
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr IconText {axi_qpsk_tx_s_axi_awaddr}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awaddr IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Name {axi_qpsk_tx_s_axi_awvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid IconText {axi_qpsk_tx_s_axi_awvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Name {axi_qpsk_tx_s_axi_awready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready IconText {axi_qpsk_tx_s_axi_awready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_awready IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Name {axi_qpsk_tx_s_axi_wdata}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Width 32
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata IconText {axi_qpsk_tx_s_axi_wdata}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wdata IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Name {axi_qpsk_tx_s_axi_wstrb}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Width 4
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb IconText {axi_qpsk_tx_s_axi_wstrb}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wstrb IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Name {axi_qpsk_tx_s_axi_wvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid IconText {axi_qpsk_tx_s_axi_wvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Name {axi_qpsk_tx_s_axi_wready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready IconText {axi_qpsk_tx_s_axi_wready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_wready IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Name {axi_qpsk_tx_s_axi_bresp}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Width 2
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp IconText {axi_qpsk_tx_s_axi_bresp}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bresp IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Name {axi_qpsk_tx_s_axi_bvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid IconText {axi_qpsk_tx_s_axi_bvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Name {axi_qpsk_tx_s_axi_bready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready IconText {axi_qpsk_tx_s_axi_bready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_bready IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Name {axi_qpsk_tx_s_axi_araddr}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Width 7
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr IconText {axi_qpsk_tx_s_axi_araddr}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_araddr IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Name {axi_qpsk_tx_s_axi_arvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid IconText {axi_qpsk_tx_s_axi_arvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Name {axi_qpsk_tx_s_axi_arready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready IconText {axi_qpsk_tx_s_axi_arready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_arready IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Name {axi_qpsk_tx_s_axi_rdata}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Width 32
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata IconText {axi_qpsk_tx_s_axi_rdata}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rdata IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Name {axi_qpsk_tx_s_axi_rresp}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Width 2
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp IconText {axi_qpsk_tx_s_axi_rresp}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rresp IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Name {axi_qpsk_tx_s_axi_rvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid IconText {axi_qpsk_tx_s_axi_rvalid}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Direction out
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rvalid IOStandard {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Name {axi_qpsk_tx_s_axi_rready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Type -
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready ArithmeticType xlUnsigned
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready BinaryPoint 0
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Width 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready DatFile {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready IconText {axi_qpsk_tx_s_axi_rready}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Direction in
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Period 1
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Interface 5
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready InterfaceName {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready InterfaceString {WIRE_AXI_LITE}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready ClockDomain {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready Locs {}
	dict set TopLevelPortInterface axi_qpsk_tx_s_axi_rready IOStandard {}
	dict set TopLevelPortInterface clk Name {clk}
	dict set TopLevelPortInterface clk Type -
	dict set TopLevelPortInterface clk ArithmeticType xlUnsigned
	dict set TopLevelPortInterface clk BinaryPoint 0
	dict set TopLevelPortInterface clk Width 1
	dict set TopLevelPortInterface clk DatFile {}
	dict set TopLevelPortInterface clk Direction in
	dict set TopLevelPortInterface clk Period 1
	dict set TopLevelPortInterface clk Interface 6
	dict set TopLevelPortInterface clk InterfaceName {}
	dict set TopLevelPortInterface clk InterfaceString {CLOCK}
	dict set TopLevelPortInterface clk ClockDomain {axi_qpsk_tx}
	dict set TopLevelPortInterface clk Locs {}
	dict set TopLevelPortInterface clk IOStandard {}
	dict set TopLevelPortInterface clk AssociatedInterfaces {axi_qpsk_tx_s_axi }
	dict set TopLevelPortInterface clk AssociatedResets {axi_qpsk_tx_aresetn }
	set MemoryMappedPort {}
	dict set MemoryMappedPort transfertime Name {transfertime}
	dict set MemoryMappedPort transfertime Type UFix_32_0
	dict set MemoryMappedPort transfertime ArithmeticType xlUnsigned
	dict set MemoryMappedPort transfertime BinaryPoint 0
	dict set MemoryMappedPort transfertime Width 32
	dict set MemoryMappedPort transfertime DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_transfertime.dat}
	dict set MemoryMappedPort transfertime AddressOffset 60
	dict set MemoryMappedPort transfertime IconText {TransferTime}
	dict set MemoryMappedPort transfertime Direction in
	dict set MemoryMappedPort transfertime Period 1
	dict set MemoryMappedPort transfertime Interface 2
	dict set MemoryMappedPort transfertime InterfaceName {}
	dict set MemoryMappedPort transfertime InterfaceString {CONTROL}
	dict set MemoryMappedPort transfertime ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort transfertime Locs {}
	dict set MemoryMappedPort transfertime IOStandard {}
	dict set MemoryMappedPort transfersymbol Name {transfersymbol}
	dict set MemoryMappedPort transfersymbol Type UFix_32_0
	dict set MemoryMappedPort transfersymbol ArithmeticType xlUnsigned
	dict set MemoryMappedPort transfersymbol BinaryPoint 0
	dict set MemoryMappedPort transfersymbol Width 32
	dict set MemoryMappedPort transfersymbol DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_transfersymbol.dat}
	dict set MemoryMappedPort transfersymbol AddressOffset 0
	dict set MemoryMappedPort transfersymbol IconText {TransferSymbol}
	dict set MemoryMappedPort transfersymbol Direction in
	dict set MemoryMappedPort transfersymbol Period 1
	dict set MemoryMappedPort transfersymbol Interface 2
	dict set MemoryMappedPort transfersymbol InterfaceName {}
	dict set MemoryMappedPort transfersymbol InterfaceString {CONTROL}
	dict set MemoryMappedPort transfersymbol ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort transfersymbol Locs {}
	dict set MemoryMappedPort transfersymbol IOStandard {}
	dict set MemoryMappedPort transferfft Name {transferfft}
	dict set MemoryMappedPort transferfft Type UFix_32_0
	dict set MemoryMappedPort transferfft ArithmeticType xlUnsigned
	dict set MemoryMappedPort transferfft BinaryPoint 0
	dict set MemoryMappedPort transferfft Width 32
	dict set MemoryMappedPort transferfft DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_transferfft.dat}
	dict set MemoryMappedPort transferfft AddressOffset 4
	dict set MemoryMappedPort transferfft IconText {TransferFFT}
	dict set MemoryMappedPort transferfft Direction in
	dict set MemoryMappedPort transferfft Period 1
	dict set MemoryMappedPort transferfft Interface 2
	dict set MemoryMappedPort transferfft InterfaceName {}
	dict set MemoryMappedPort transferfft InterfaceString {CONTROL}
	dict set MemoryMappedPort transferfft ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort transferfft Locs {}
	dict set MemoryMappedPort transferfft IOStandard {}
	dict set MemoryMappedPort simulateinterface Name {simulateinterface}
	dict set MemoryMappedPort simulateinterface Type UFix_32_0
	dict set MemoryMappedPort simulateinterface ArithmeticType xlUnsigned
	dict set MemoryMappedPort simulateinterface BinaryPoint 0
	dict set MemoryMappedPort simulateinterface Width 32
	dict set MemoryMappedPort simulateinterface DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_simulateinterface.dat}
	dict set MemoryMappedPort simulateinterface AddressOffset 64
	dict set MemoryMappedPort simulateinterface IconText {SimulateInterface}
	dict set MemoryMappedPort simulateinterface Direction in
	dict set MemoryMappedPort simulateinterface Period 1
	dict set MemoryMappedPort simulateinterface Interface 2
	dict set MemoryMappedPort simulateinterface InterfaceName {}
	dict set MemoryMappedPort simulateinterface InterfaceString {CONTROL}
	dict set MemoryMappedPort simulateinterface ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort simulateinterface Locs {}
	dict set MemoryMappedPort simulateinterface IOStandard {}
	dict set MemoryMappedPort resettime Name {resettime}
	dict set MemoryMappedPort resettime Type UFix_32_0
	dict set MemoryMappedPort resettime ArithmeticType xlUnsigned
	dict set MemoryMappedPort resettime BinaryPoint 0
	dict set MemoryMappedPort resettime Width 32
	dict set MemoryMappedPort resettime DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_resettime.dat}
	dict set MemoryMappedPort resettime AddressOffset 48
	dict set MemoryMappedPort resettime IconText {ResetTime}
	dict set MemoryMappedPort resettime Direction in
	dict set MemoryMappedPort resettime Period 1
	dict set MemoryMappedPort resettime Interface 2
	dict set MemoryMappedPort resettime InterfaceName {}
	dict set MemoryMappedPort resettime InterfaceString {CONTROL}
	dict set MemoryMappedPort resettime ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort resettime Locs {}
	dict set MemoryMappedPort resettime IOStandard {}
	dict set MemoryMappedPort resetsymbol Name {resetsymbol}
	dict set MemoryMappedPort resetsymbol Type UFix_32_0
	dict set MemoryMappedPort resetsymbol ArithmeticType xlUnsigned
	dict set MemoryMappedPort resetsymbol BinaryPoint 0
	dict set MemoryMappedPort resetsymbol Width 32
	dict set MemoryMappedPort resetsymbol DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_resetsymbol.dat}
	dict set MemoryMappedPort resetsymbol AddressOffset 8
	dict set MemoryMappedPort resetsymbol IconText {ResetSymbol}
	dict set MemoryMappedPort resetsymbol Direction in
	dict set MemoryMappedPort resetsymbol Period 1
	dict set MemoryMappedPort resetsymbol Interface 2
	dict set MemoryMappedPort resetsymbol InterfaceName {}
	dict set MemoryMappedPort resetsymbol InterfaceString {CONTROL}
	dict set MemoryMappedPort resetsymbol ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort resetsymbol Locs {}
	dict set MemoryMappedPort resetsymbol IOStandard {}
	dict set MemoryMappedPort resetfft Name {resetfft}
	dict set MemoryMappedPort resetfft Type UFix_32_0
	dict set MemoryMappedPort resetfft ArithmeticType xlUnsigned
	dict set MemoryMappedPort resetfft BinaryPoint 0
	dict set MemoryMappedPort resetfft Width 32
	dict set MemoryMappedPort resetfft DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_resetfft.dat}
	dict set MemoryMappedPort resetfft AddressOffset 12
	dict set MemoryMappedPort resetfft IconText {ResetFFT}
	dict set MemoryMappedPort resetfft Direction in
	dict set MemoryMappedPort resetfft Period 6400
	dict set MemoryMappedPort resetfft Interface 2
	dict set MemoryMappedPort resetfft InterfaceName {}
	dict set MemoryMappedPort resetfft InterfaceString {CONTROL}
	dict set MemoryMappedPort resetfft ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort resetfft Locs {}
	dict set MemoryMappedPort resetfft IOStandard {}
	dict set MemoryMappedPort packetsizetime Name {packetsizetime}
	dict set MemoryMappedPort packetsizetime Type UFix_32_0
	dict set MemoryMappedPort packetsizetime ArithmeticType xlUnsigned
	dict set MemoryMappedPort packetsizetime BinaryPoint 0
	dict set MemoryMappedPort packetsizetime Width 32
	dict set MemoryMappedPort packetsizetime DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_packetsizetime.dat}
	dict set MemoryMappedPort packetsizetime AddressOffset 52
	dict set MemoryMappedPort packetsizetime IconText {PacketSizeTime}
	dict set MemoryMappedPort packetsizetime Direction in
	dict set MemoryMappedPort packetsizetime Period 1
	dict set MemoryMappedPort packetsizetime Interface 2
	dict set MemoryMappedPort packetsizetime InterfaceName {}
	dict set MemoryMappedPort packetsizetime InterfaceString {CONTROL}
	dict set MemoryMappedPort packetsizetime ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort packetsizetime Locs {}
	dict set MemoryMappedPort packetsizetime IOStandard {}
	dict set MemoryMappedPort packetsizesymbol Name {packetsizesymbol}
	dict set MemoryMappedPort packetsizesymbol Type UFix_32_0
	dict set MemoryMappedPort packetsizesymbol ArithmeticType xlUnsigned
	dict set MemoryMappedPort packetsizesymbol BinaryPoint 0
	dict set MemoryMappedPort packetsizesymbol Width 32
	dict set MemoryMappedPort packetsizesymbol DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_packetsizesymbol.dat}
	dict set MemoryMappedPort packetsizesymbol AddressOffset 16
	dict set MemoryMappedPort packetsizesymbol IconText {PacketSizeSymbol}
	dict set MemoryMappedPort packetsizesymbol Direction in
	dict set MemoryMappedPort packetsizesymbol Period 1
	dict set MemoryMappedPort packetsizesymbol Interface 2
	dict set MemoryMappedPort packetsizesymbol InterfaceName {}
	dict set MemoryMappedPort packetsizesymbol InterfaceString {CONTROL}
	dict set MemoryMappedPort packetsizesymbol ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort packetsizesymbol Locs {}
	dict set MemoryMappedPort packetsizesymbol IOStandard {}
	dict set MemoryMappedPort packetsizerf Name {packetsizerf}
	dict set MemoryMappedPort packetsizerf Type UFix_32_0
	dict set MemoryMappedPort packetsizerf ArithmeticType xlUnsigned
	dict set MemoryMappedPort packetsizerf BinaryPoint 0
	dict set MemoryMappedPort packetsizerf Width 32
	dict set MemoryMappedPort packetsizerf DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_packetsizerf.dat}
	dict set MemoryMappedPort packetsizerf AddressOffset 20
	dict set MemoryMappedPort packetsizerf IconText {PacketSizeRF}
	dict set MemoryMappedPort packetsizerf Direction in
	dict set MemoryMappedPort packetsizerf Period 51200
	dict set MemoryMappedPort packetsizerf Interface 2
	dict set MemoryMappedPort packetsizerf InterfaceName {}
	dict set MemoryMappedPort packetsizerf InterfaceString {CONTROL}
	dict set MemoryMappedPort packetsizerf ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort packetsizerf Locs {}
	dict set MemoryMappedPort packetsizerf IOStandard {}
	dict set MemoryMappedPort packetsizefft Name {packetsizefft}
	dict set MemoryMappedPort packetsizefft Type UFix_32_0
	dict set MemoryMappedPort packetsizefft ArithmeticType xlUnsigned
	dict set MemoryMappedPort packetsizefft BinaryPoint 0
	dict set MemoryMappedPort packetsizefft Width 32
	dict set MemoryMappedPort packetsizefft DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_packetsizefft.dat}
	dict set MemoryMappedPort packetsizefft AddressOffset 24
	dict set MemoryMappedPort packetsizefft IconText {PacketSizeFFT}
	dict set MemoryMappedPort packetsizefft Direction in
	dict set MemoryMappedPort packetsizefft Period 1
	dict set MemoryMappedPort packetsizefft Interface 2
	dict set MemoryMappedPort packetsizefft InterfaceName {}
	dict set MemoryMappedPort packetsizefft InterfaceString {CONTROL}
	dict set MemoryMappedPort packetsizefft ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort packetsizefft Locs {}
	dict set MemoryMappedPort packetsizefft IOStandard {}
	dict set MemoryMappedPort outputgain Name {outputgain}
	dict set MemoryMappedPort outputgain Type UFix_32_0
	dict set MemoryMappedPort outputgain ArithmeticType xlUnsigned
	dict set MemoryMappedPort outputgain BinaryPoint 0
	dict set MemoryMappedPort outputgain Width 32
	dict set MemoryMappedPort outputgain DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_outputgain.dat}
	dict set MemoryMappedPort outputgain AddressOffset 44
	dict set MemoryMappedPort outputgain IconText {OutputGain}
	dict set MemoryMappedPort outputgain Direction in
	dict set MemoryMappedPort outputgain Period 6400
	dict set MemoryMappedPort outputgain Interface 2
	dict set MemoryMappedPort outputgain InterfaceName {}
	dict set MemoryMappedPort outputgain InterfaceString {CONTROL}
	dict set MemoryMappedPort outputgain ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort outputgain Locs {}
	dict set MemoryMappedPort outputgain IOStandard {}
	dict set MemoryMappedPort lfsr_rst Name {lfsr_rst}
	dict set MemoryMappedPort lfsr_rst Type UFix_32_0
	dict set MemoryMappedPort lfsr_rst ArithmeticType xlUnsigned
	dict set MemoryMappedPort lfsr_rst BinaryPoint 0
	dict set MemoryMappedPort lfsr_rst Width 32
	dict set MemoryMappedPort lfsr_rst DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_lfsr_rst.dat}
	dict set MemoryMappedPort lfsr_rst AddressOffset 28
	dict set MemoryMappedPort lfsr_rst IconText {LFSR_rst}
	dict set MemoryMappedPort lfsr_rst Direction in
	dict set MemoryMappedPort lfsr_rst Period 51200
	dict set MemoryMappedPort lfsr_rst Interface 2
	dict set MemoryMappedPort lfsr_rst InterfaceName {}
	dict set MemoryMappedPort lfsr_rst InterfaceString {CONTROL}
	dict set MemoryMappedPort lfsr_rst ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort lfsr_rst Locs {}
	dict set MemoryMappedPort lfsr_rst IOStandard {}
	dict set MemoryMappedPort enable Name {enable}
	dict set MemoryMappedPort enable Type UFix_32_0
	dict set MemoryMappedPort enable ArithmeticType xlUnsigned
	dict set MemoryMappedPort enable BinaryPoint 0
	dict set MemoryMappedPort enable Width 32
	dict set MemoryMappedPort enable DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_enable.dat}
	dict set MemoryMappedPort enable AddressOffset 32
	dict set MemoryMappedPort enable IconText {Enable}
	dict set MemoryMappedPort enable Direction in
	dict set MemoryMappedPort enable Period 51200
	dict set MemoryMappedPort enable Interface 2
	dict set MemoryMappedPort enable InterfaceName {}
	dict set MemoryMappedPort enable InterfaceString {CONTROL}
	dict set MemoryMappedPort enable ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort enable Locs {}
	dict set MemoryMappedPort enable IOStandard {}
	dict set MemoryMappedPort bypassgain Name {bypassgain}
	dict set MemoryMappedPort bypassgain Type UFix_32_0
	dict set MemoryMappedPort bypassgain ArithmeticType xlUnsigned
	dict set MemoryMappedPort bypassgain BinaryPoint 0
	dict set MemoryMappedPort bypassgain Width 32
	dict set MemoryMappedPort bypassgain DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_bypassgain.dat}
	dict set MemoryMappedPort bypassgain AddressOffset 68
	dict set MemoryMappedPort bypassgain IconText {BypassGain}
	dict set MemoryMappedPort bypassgain Direction in
	dict set MemoryMappedPort bypassgain Period 6400
	dict set MemoryMappedPort bypassgain Interface 2
	dict set MemoryMappedPort bypassgain InterfaceName {}
	dict set MemoryMappedPort bypassgain InterfaceString {CONTROL}
	dict set MemoryMappedPort bypassgain ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort bypassgain Locs {}
	dict set MemoryMappedPort bypassgain IOStandard {}
	dict set MemoryMappedPort autorestarttime Name {autorestarttime}
	dict set MemoryMappedPort autorestarttime Type UFix_32_0
	dict set MemoryMappedPort autorestarttime ArithmeticType xlUnsigned
	dict set MemoryMappedPort autorestarttime BinaryPoint 0
	dict set MemoryMappedPort autorestarttime Width 32
	dict set MemoryMappedPort autorestarttime DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_autorestarttime.dat}
	dict set MemoryMappedPort autorestarttime AddressOffset 56
	dict set MemoryMappedPort autorestarttime IconText {AutoRestartTime}
	dict set MemoryMappedPort autorestarttime Direction in
	dict set MemoryMappedPort autorestarttime Period 1
	dict set MemoryMappedPort autorestarttime Interface 2
	dict set MemoryMappedPort autorestarttime InterfaceName {}
	dict set MemoryMappedPort autorestarttime InterfaceString {CONTROL}
	dict set MemoryMappedPort autorestarttime ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort autorestarttime Locs {}
	dict set MemoryMappedPort autorestarttime IOStandard {}
	dict set MemoryMappedPort autorestartsymbol Name {autorestartsymbol}
	dict set MemoryMappedPort autorestartsymbol Type UFix_32_0
	dict set MemoryMappedPort autorestartsymbol ArithmeticType xlUnsigned
	dict set MemoryMappedPort autorestartsymbol BinaryPoint 0
	dict set MemoryMappedPort autorestartsymbol Width 32
	dict set MemoryMappedPort autorestartsymbol DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_autorestartsymbol.dat}
	dict set MemoryMappedPort autorestartsymbol AddressOffset 36
	dict set MemoryMappedPort autorestartsymbol IconText {AutoRestartSymbol}
	dict set MemoryMappedPort autorestartsymbol Direction in
	dict set MemoryMappedPort autorestartsymbol Period 1
	dict set MemoryMappedPort autorestartsymbol Interface 2
	dict set MemoryMappedPort autorestartsymbol InterfaceName {}
	dict set MemoryMappedPort autorestartsymbol InterfaceString {CONTROL}
	dict set MemoryMappedPort autorestartsymbol ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort autorestartsymbol Locs {}
	dict set MemoryMappedPort autorestartsymbol IOStandard {}
	dict set MemoryMappedPort autorestartfft Name {autorestartfft}
	dict set MemoryMappedPort autorestartfft Type UFix_32_0
	dict set MemoryMappedPort autorestartfft ArithmeticType xlUnsigned
	dict set MemoryMappedPort autorestartfft BinaryPoint 0
	dict set MemoryMappedPort autorestartfft Width 32
	dict set MemoryMappedPort autorestartfft DatFile {axi_qpsk_tx_axi_qpsk_generator_ctrl_autorestartfft.dat}
	dict set MemoryMappedPort autorestartfft AddressOffset 40
	dict set MemoryMappedPort autorestartfft IconText {AutoRestartFFT}
	dict set MemoryMappedPort autorestartfft Direction in
	dict set MemoryMappedPort autorestartfft Period 1
	dict set MemoryMappedPort autorestartfft Interface 2
	dict set MemoryMappedPort autorestartfft InterfaceName {}
	dict set MemoryMappedPort autorestartfft InterfaceString {CONTROL}
	dict set MemoryMappedPort autorestartfft ClockDomain {axi_qpsk_tx}
	dict set MemoryMappedPort autorestartfft Locs {}
	dict set MemoryMappedPort autorestartfft IOStandard {}
}

source SgPaProject.tcl
::xilinx::dsp::planaheadworker::dsp_create_project